# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/get-woke/woke
    rev: v0.19.0
    hooks:
    -   id: woke-from-source
        files: .*
-   repo: local
    hooks:
    -   id: run-tests
        name: run run-tests script
        stages:
          [commit-msg, post-checkout, post-commit, post-merge, post-rewrite,
           commit, merge-commit, push, prepare-commit-msg]
        language: script
        entry: ./run-tests
        always_run: true
        exclude: '.pre-commit-config.yaml|etc/crontab'
